---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - orca.paermini.com
  resources:
  - scenariotemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orca.paermini.com
  resources:
  - scenariotemplates/finalizers
  verbs:
  - update
- apiGroups:
  - orca.paermini.com
  resources:
  - scenariotemplates/status
  verbs:
  - get
  - patch
  - update
