# permissions for end users to edit scenariotemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scenariotemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orca-scenario-template
    app.kubernetes.io/part-of: orca-scenario-template
    app.kubernetes.io/managed-by: kustomize
  name: scenariotemplate-editor-role
rules:
- apiGroups:
  - orca.paermini.com
  resources:
  - scenariotemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orca.paermini.com
  resources:
  - scenariotemplates/status
  verbs:
  - get
