# permissions for end users to view scenariotemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scenariotemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orca-scenario-template
    app.kubernetes.io/part-of: orca-scenario-template
    app.kubernetes.io/managed-by: kustomize
  name: scenariotemplate-viewer-role
rules:
- apiGroups:
  - orca.paermini.com
  resources:
  - scenariotemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - orca.paermini.com
  resources:
  - scenariotemplates/status
  verbs:
  - get
