//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	orca_mqtt_clientapiv1beta1 "github.com/paolerm/orca-mqtt-client/api/v1beta1"
	apiv1beta1 "github.com/paolerm/orca-opcua-server/api/v1beta1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioTemplate) DeepCopyInto(out *ScenarioTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioTemplate.
func (in *ScenarioTemplate) DeepCopy() *ScenarioTemplate {
	if in == nil {
		return nil
	}
	out := new(ScenarioTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScenarioTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioTemplateList) DeepCopyInto(out *ScenarioTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ScenarioTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioTemplateList.
func (in *ScenarioTemplateList) DeepCopy() *ScenarioTemplateList {
	if in == nil {
		return nil
	}
	out := new(ScenarioTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ScenarioTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioTemplateSpec) DeepCopyInto(out *ScenarioTemplateSpec) {
	*out = *in
	if in.OpcuaSiteSpec != nil {
		in, out := &in.OpcuaSiteSpec, &out.OpcuaSiteSpec
		*out = make([]apiv1beta1.OpcuaServerSpec, len(*in))
		copy(*out, *in)
	}
	if in.MqttClientSiteSpec != nil {
		in, out := &in.MqttClientSiteSpec, &out.MqttClientSiteSpec
		*out = make([]orca_mqtt_clientapiv1beta1.MqttClientSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioTemplateSpec.
func (in *ScenarioTemplateSpec) DeepCopy() *ScenarioTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ScenarioTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioTemplateStatus) DeepCopyInto(out *ScenarioTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioTemplateStatus.
func (in *ScenarioTemplateStatus) DeepCopy() *ScenarioTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ScenarioTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
